name: "Scan Docker configs"
description: "Scan Docker configs when PR is open"
author: "Anatoliy Shvarts"

inputs:
  scan_dir:
    description: 'Path to directory to scan'
    required: true
    default: './'
runs:
  using: "composite"
  steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Run docker scanner
      run: |
        export IMAGE_NAME="quiner/docker_scanner:$SCANNER_VERSION"
        echo "Using image: $IMAGE_NAME"
        docker pull "$IMAGE_NAME"
        docker run -v "$SCAN_DIR"/:/scan_dir:ro -v /var/run/docker.sock:/var/run/docker.sock --env scan_dir=/scan_dir "$IMAGE_NAME"
      shell: bash
      env:
        SCANNER_VERSION: 0.0.1
        SCAN_DIR: ${{ inputs.scan_dir }}

branding:
  icon: box
  color: black